name: Hello                        # 워크플로명                                
on:
  push:                            # 이벤트(푸시할 때 발생)
jobs:                              # 작업(잡)
  hello:                           # 작업명  
    runs-on: ubuntu-latest         # 러너
    steps:                         # 스텝 정의
      - run: echo "Hello, world!"  # 셀 명렁 실행
      - uses: actions/checkout@v4  # 액션 호출

      

    
